# Generated by Django 5.0.4 on 2024-05-24 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="course.course",
                verbose_name="оплаченный курс",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="статус оплаты"),
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course.lesson",
                verbose_name="оплаченный урок",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.CharField(
                blank=True, max_length=180, null=True, verbose_name="сессия для оплаты"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="the_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="оплативший_пользователь",
            ),
        ),
    ]
