# Generated by Django 5.0.4 on 2024-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment_course_payment_lesson_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку для оплаты",
                max_length=400,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
