# Generated by Django 5.0.4 on 2024-05-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_options_remove_user_username_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lesson",
        ),
    ]
