version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'

  db:
    restart: always
    image: postgres:14.7-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: celery -A drf worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A drf beat -l INFO -S django
    depends_on:
      - redis
      - app

volumes:
  postgres_data:
