# Generated by Django 5.0.4 on 2024-06-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_owner_lesson_owner_subscription_user"),
        ("course", "0002_initial"),
    ]

    operations = []
