# Generated by Django 5.0.4 on 2024-05-21 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="link",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="owner",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="курс",
            ),
        ),
    ]
