# Generated by Django 5.0.4 on 2024-05-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_rename_course_lesson_course_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course_course",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="course_course",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_course",
                to="course.course",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_course",
                to="course.course",
            ),
        ),
    ]
