# Generated by Django 5.0.4 on 2024-05-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_remove_lesson_course_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course",
            new_name="course_les",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="course",
            new_name="course_sub",
        ),
    ]
