# Generated by Django 5.0.4 on 2024-05-22 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_rename_course_lesson_course_les_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="course_les",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="course_sub",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="lessons",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.course",
                verbose_name="курс",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
